spec:
  description: Replaced string with new string 
  projects:
    - ~user.name_site.com
  replacements:
    - from: old string 1
      to: new string 1
    - from: old string 2
      to: new string 2
