versions:
  - name: Voyager
    current:
      name: DockerfileSpider
      params:
        path: ~/path/to/your/Dockerfile
    latest:
      name: GithubReleaseSpider
      params:
        owner: appscode
        repository: voyager
#  - name: Jenkins
#    current:
#      name: DockerfileSpider
#      params:
#          path: ~/path/to/your/Dockerfile
#    latest:
#      name: JenkinsStableSpider
#      # This spider does not take arguments
#      params: {}