versions:
  - name: Voyager
    current:
      name: DockerfileSpider
      params:
        path: ~/dev/electrolux/kubernetes-voyager-deployment/docker/Dockerfile
    latest:
      name: GithubReleaseSpider
      params:
        owner: appscode
        repository: voyager
  - name: Jenkins
    current:
      name: DockerfileSpider
      params:
          path: ~/dev/electrolux/kubernetes-jenkins-deployment/docker/Dockerfile
    latest:
      name: JenkinsStableSpider
      params: {}